"""remove subnet_id coloumn from ip address

Revision ID: 40712b41e631
Revises: da6a2dfe9a63
Create Date: 2025-02-24 22:58:03.514388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40712b41e631'
down_revision: Union[str, None] = 'da6a2dfe9a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
