"""update models

Revision ID: 5174725312ad
Revises: ba1fd5e0daab
Create Date: 2025-02-23 23:50:51.076929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5174725312ad'
down_revision: Union[str, None] = 'ba1fd5e0daab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_addresses', sa.Column('prefix_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ip_addresses', 'ipam_prefix', ['prefix_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_addresses', type_='foreignkey')
    op.drop_column('ip_addresses', 'prefix_id')
    # ### end Alembic commands ###
