"""Add site_id and tenant_id to devices

Revision ID: 5b2c70227a85
Revises: d384e835f4dd
Create Date: 2025-03-01 00:14:31.340582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5b2c70227a85'
down_revision = 'd384e835f4dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'sites', ['site_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'tenant_id')
    op.drop_column('devices', 'site_id')
    # ### end Alembic commands ###
