"""add credential model

Revision ID: 6462281a55cb
Revises: 8730762a456d
Create Date: 2025-03-02 12:55:51.033090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6462281a55cb'
down_revision = '8730762a456d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asn_ranges', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('asns', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('devices', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interfaces', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('locations', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rirs', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('roles', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('route_targets', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vlan_groups', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vlans', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vlans', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vlan_groups', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('route_targets', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roles', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rirs', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interfaces', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asns', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asn_ranges', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
