"""making name field unique in region

Revision ID: 83de508981bd
Revises: a626cf22a621
Create Date: 2025-03-01 10:20:38.878269

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '83de508981bd'
down_revision = 'a626cf22a621'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the unique constraint to the region name
    op.create_unique_constraint('uq_region_name', 'regions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the unique constraint from the region name
    op.drop_constraint('uq_region_name', 'regions', type_='unique')
    # ### end Alembic commands ###
