"""removed unused fields in sites

Revision ID: 913aad517986
Revises: b991ffca972d
Create Date: 2025-02-24 21:36:04.685163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '913aad517986'
down_revision: Union[str, None] = 'b991ffca972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipam_site', 'shipping_address')
    op.drop_column('ipam_site', 'facility')
    op.drop_column('ipam_site', 'contact_name')
    op.drop_column('ipam_site', 'longitude')
    op.drop_column('ipam_site', 'contact_email')
    op.drop_column('ipam_site', 'comments')
    op.drop_column('ipam_site', 'contact_phone')
    op.drop_column('ipam_site', 'physical_address')
    op.drop_column('ipam_site', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipam_site', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('physical_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('facility', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ipam_site', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
