"""Update site and location models to match NetBox spec

Revision ID: b014f3a0eef1
Revises: 001
Create Date: 2025-02-22 14:57:34.903082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b014f3a0eef1'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipam_location', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index('ix_ipam_location_slug', table_name='ipam_location')
    op.create_index(op.f('ix_ipam_location_slug'), 'ipam_location', ['slug'], unique=True)
    op.drop_index('ix_ipam_region_slug', table_name='ipam_region')
    op.create_index(op.f('ix_ipam_region_slug'), 'ipam_region', ['slug'], unique=True)
    op.add_column('ipam_site', sa.Column('facility', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ipam_site', sa.Column('physical_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ipam_site', sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ipam_site', sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ipam_site', sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ipam_site', sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ipam_site', sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_ipam_site_slug', table_name='ipam_site')
    op.create_index(op.f('ix_ipam_site_slug'), 'ipam_site', ['slug'], unique=True)
    op.drop_column('ipam_site', 'address')
    op.drop_index('ix_ipam_sitegroup_slug', table_name='ipam_sitegroup')
    op.create_index(op.f('ix_ipam_sitegroup_slug'), 'ipam_sitegroup', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipam_sitegroup_slug'), table_name='ipam_sitegroup')
    op.create_index('ix_ipam_sitegroup_slug', 'ipam_sitegroup', ['slug'], unique=False)
    op.add_column('ipam_site', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_ipam_site_slug'), table_name='ipam_site')
    op.create_index('ix_ipam_site_slug', 'ipam_site', ['slug'], unique=False)
    op.drop_column('ipam_site', 'comments')
    op.drop_column('ipam_site', 'contact_email')
    op.drop_column('ipam_site', 'contact_phone')
    op.drop_column('ipam_site', 'contact_name')
    op.drop_column('ipam_site', 'shipping_address')
    op.drop_column('ipam_site', 'physical_address')
    op.drop_column('ipam_site', 'facility')
    op.drop_index(op.f('ix_ipam_region_slug'), table_name='ipam_region')
    op.create_index('ix_ipam_region_slug', 'ipam_region', ['slug'], unique=False)
    op.drop_index(op.f('ix_ipam_location_slug'), table_name='ipam_location')
    op.create_index('ix_ipam_location_slug', 'ipam_location', ['slug'], unique=False)
    op.drop_column('ipam_location', 'tenant_id')
    # ### end Alembic commands ###
