"""initial migration

Revision ID: ba1fd5e0daab
Revises: 
Create Date: 2025-02-23 23:45:51.002783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba1fd5e0daab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('changes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ipam_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_region_name'), 'ipam_region', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_region_slug'), 'ipam_region', ['slug'], unique=True)
    op.create_table('ipam_rir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_rir_name'), 'ipam_rir', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_rir_slug'), 'ipam_rir', ['slug'], unique=False)
    op.create_table('ipam_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_role_name'), 'ipam_role', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_role_slug'), 'ipam_role', ['slug'], unique=False)
    op.create_table('ipam_sitegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ipam_sitegroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_sitegroup_name'), 'ipam_sitegroup', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_sitegroup_slug'), 'ipam_sitegroup', ['slug'], unique=True)
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlans_vid'), 'vlans', ['vid'], unique=False)
    op.create_table('vrfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rd')
    )
    op.create_index(op.f('ix_vrfs_name'), 'vrfs', ['name'], unique=False)
    op.create_table('ipam_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rir_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['rir_id'], ['ipam_rir.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_aggregate_prefix'), 'ipam_aggregate', ['prefix'], unique=False)
    op.create_table('ipam_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('site_group_id', sa.Integer(), nullable=True),
    sa.Column('facility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physical_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['ipam_region.id'], ),
    sa.ForeignKeyConstraint(['site_group_id'], ['ipam_sitegroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_site_name'), 'ipam_site', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_site_slug'), 'ipam_site', ['slug'], unique=True)
    op.create_index(op.f('ix_ipam_site_status'), 'ipam_site', ['status'], unique=False)
    op.create_table('subnets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix_length', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ),
    sa.ForeignKeyConstraint(['vrf_id'], ['vrfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnets_network'), 'subnets', ['network'], unique=False)
    op.create_index(op.f('ix_subnets_prefix_length'), 'subnets', ['prefix_length'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subnet_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dns_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_address'), 'ip_addresses', ['address'], unique=False)
    op.create_table('ipam_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ipam_location.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['ipam_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_location_name'), 'ipam_location', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_location_slug'), 'ipam_location', ['slug'], unique=True)
    op.create_index(op.f('ix_ipam_location_status'), 'ipam_location', ['status'], unique=False)
    op.create_table('ipam_prefix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('aggregate_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregate_id'], ['ipam_aggregate.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ipam_role.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['ipam_site.id'], ),
    sa.ForeignKeyConstraint(['vrf_id'], ['vrfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_prefix_prefix'), 'ipam_prefix', ['prefix'], unique=False)
    op.create_index(op.f('ix_ipam_prefix_status'), 'ipam_prefix', ['status'], unique=False)
    op.create_table('ipam_ip_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix_id', sa.Integer(), nullable=False),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prefix_id'], ['ipam_prefix.id'], ),
    sa.ForeignKeyConstraint(['vrf_id'], ['vrfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_ip_range_end_address'), 'ipam_ip_range', ['end_address'], unique=False)
    op.create_index(op.f('ix_ipam_ip_range_start_address'), 'ipam_ip_range', ['start_address'], unique=False)
    op.create_index(op.f('ix_ipam_ip_range_status'), 'ipam_ip_range', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipam_ip_range_status'), table_name='ipam_ip_range')
    op.drop_index(op.f('ix_ipam_ip_range_start_address'), table_name='ipam_ip_range')
    op.drop_index(op.f('ix_ipam_ip_range_end_address'), table_name='ipam_ip_range')
    op.drop_table('ipam_ip_range')
    op.drop_index(op.f('ix_ipam_prefix_status'), table_name='ipam_prefix')
    op.drop_index(op.f('ix_ipam_prefix_prefix'), table_name='ipam_prefix')
    op.drop_table('ipam_prefix')
    op.drop_index(op.f('ix_ipam_location_status'), table_name='ipam_location')
    op.drop_index(op.f('ix_ipam_location_slug'), table_name='ipam_location')
    op.drop_index(op.f('ix_ipam_location_name'), table_name='ipam_location')
    op.drop_table('ipam_location')
    op.drop_index(op.f('ix_ip_addresses_address'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_subnets_prefix_length'), table_name='subnets')
    op.drop_index(op.f('ix_subnets_network'), table_name='subnets')
    op.drop_table('subnets')
    op.drop_index(op.f('ix_ipam_site_status'), table_name='ipam_site')
    op.drop_index(op.f('ix_ipam_site_slug'), table_name='ipam_site')
    op.drop_index(op.f('ix_ipam_site_name'), table_name='ipam_site')
    op.drop_table('ipam_site')
    op.drop_index(op.f('ix_ipam_aggregate_prefix'), table_name='ipam_aggregate')
    op.drop_table('ipam_aggregate')
    op.drop_index(op.f('ix_vrfs_name'), table_name='vrfs')
    op.drop_table('vrfs')
    op.drop_index(op.f('ix_vlans_vid'), table_name='vlans')
    op.drop_table('vlans')
    op.drop_index(op.f('ix_ipam_sitegroup_slug'), table_name='ipam_sitegroup')
    op.drop_index(op.f('ix_ipam_sitegroup_name'), table_name='ipam_sitegroup')
    op.drop_table('ipam_sitegroup')
    op.drop_index(op.f('ix_ipam_role_slug'), table_name='ipam_role')
    op.drop_index(op.f('ix_ipam_role_name'), table_name='ipam_role')
    op.drop_table('ipam_role')
    op.drop_index(op.f('ix_ipam_rir_slug'), table_name='ipam_rir')
    op.drop_index(op.f('ix_ipam_rir_name'), table_name='ipam_rir')
    op.drop_table('ipam_rir')
    op.drop_index(op.f('ix_ipam_region_slug'), table_name='ipam_region')
    op.drop_index(op.f('ix_ipam_region_name'), table_name='ipam_region')
    op.drop_table('ipam_region')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
