"""completely removed subnets and its refrences

Revision ID: c7de91500d53
Revises: 40712b41e631
Create Date: 2025-02-24 23:05:39.791135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7de91500d53'
down_revision: Union[str, None] = '40712b41e631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subnets_network', table_name='subnets')
    op.drop_index('ix_subnets_prefix_length', table_name='subnets')
    op.drop_table('subnets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prefix_length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vlan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vrf_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], name='subnets_vlan_id_fkey'),
    sa.ForeignKeyConstraint(['vrf_id'], ['vrfs.id'], name='subnets_vrf_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subnets_pkey')
    )
    op.create_index('ix_subnets_prefix_length', 'subnets', ['prefix_length'], unique=False)
    op.create_index('ix_subnets_network', 'subnets', ['network'], unique=False)
    # ### end Alembic commands ###
