"""Use association tables for VRF-RouteTarget relationships

Revision ID: ebc6fde71a9c
Revises: 880e86cb9029
Create Date: 2025-04-23 17:09:36.582430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ebc6fde71a9c'
down_revision = '880e86cb9029'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
